name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry run python -m pip install tox-gh-actions
        poetry install
    - name: Install bigquery-emulator
      uses: supplypike/setup-bin@v3
      with:
        uri: https://github.com/goccy/bigquery-emulator/releases/download/v0.3.1/bigquery-emulator-linux-amd64
        name: bigquery-emulator
        version: 0.3.1
    - name: Test with tox
      run: poetry run tox
    - name: Run example
      run: poetry run python examples/testing.py
